// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARUf5puZ-VldCqqlmn3a7EtGfVmaigqKQ',
    appId: '1:365381154866:web:3d3ee347a6daf475b1242b',
    messagingSenderId: '365381154866',
    projectId: 'act12-fd927',
    authDomain: 'act12-fd927.firebaseapp.com',
    storageBucket: 'act12-fd927.firebasestorage.app',
    measurementId: 'G-1WWLVNE8T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDko2Z1xU2pCaaXJ8mvqY8CHQkTy8VyEp4',
    appId: '1:365381154866:android:07905c92ef2256a6b1242b',
    messagingSenderId: '365381154866',
    projectId: 'act12-fd927',
    storageBucket: 'act12-fd927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0zJhL3L_P3zcJLrcMxXLkC8SroK8XxAY',
    appId: '1:365381154866:ios:f564a8d947b3b34eb1242b',
    messagingSenderId: '365381154866',
    projectId: 'act12-fd927',
    storageBucket: 'act12-fd927.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0zJhL3L_P3zcJLrcMxXLkC8SroK8XxAY',
    appId: '1:365381154866:ios:f564a8d947b3b34eb1242b',
    messagingSenderId: '365381154866',
    projectId: 'act12-fd927',
    storageBucket: 'act12-fd927.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARUf5puZ-VldCqqlmn3a7EtGfVmaigqKQ',
    appId: '1:365381154866:web:c53731b89cf6d59db1242b',
    messagingSenderId: '365381154866',
    projectId: 'act12-fd927',
    authDomain: 'act12-fd927.firebaseapp.com',
    storageBucket: 'act12-fd927.firebasestorage.app',
    measurementId: 'G-8C91QZPN2V',
  );
}
